---
title: "meters_EDA"
author: "Sean Koh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup-libaries}

library(tidyverse)
library(sf)
library(httr)
library(jsonlite)
library(data.table)
library(basemaps)

CRS_TARGET = "EPSG:32139"

mapbox.apikey = readChar("secure/mapbox.txt", file.info("secure/mapbox.txt")$size)
```

```{r load-data}
# Read raw meter transaction data
# raw.data <- rbind(fread("data/pems transactions jan-jun2024.csv"),
#                   fread("data/pems transactions jul-dec2024.csv")) %>%
#   rename(meter.ID = "name")

# Read street data geojson (derived from shape file)
raw.streets <- st_read("data/EPCenterline.geojson") %>%
  st_transform(CRS_TARGET) %>%
  rename(street.ID = "OBJECTID_1")

# Read street with nov transaction data
data <- fread("data/12_months.csv") %>%
  mutate(date = date(occupancy.buckets),
         hour = hour(ymd_hms(occupancy.buckets, quiet = F)),
         minute = minute(ymd_hms(occupancy.buckets, quiet = F)),
         hour = replace_na(hour, 0),
         minute = replace_na(minute, 0),
         timestamp = date + hours(hour) + minutes(minute))

# Read meters data geojson (derived from shape file)
meters <- st_read("data/meters.geojson")%>%
  st_transform(CRS_TARGET) %>%
  rename(meter.ID = "LocationID")

# Assign each meter to its nearest street
meters$street.ID <- raw.streets[st_nearest_feature(meters, raw.streets),"street.ID"] %>%
  st_drop_geometry() %>%
  unlist()

# Read parking estimates from parking capacity excel
raw.excel.estimates <- st_read("data/capacity_estimate.geojson")

```
```{r }
# Combine raw meter transaction with meter shape data
cleaned.transactions <- raw.data %>% 
  mutate(timestamp = dmy_hm(datetime),
         date = dmy(date),
         min_paid = max(min_paid, 0))

# Assign transaction ID
cleaned.transactions$transaction.ID <- seq(1, dim(raw.data)[1])

# Aggregate by transaction date
transactions.agg <- cleaned.transactions %>%
  group_by(date) %>%
  summarise(total_min = sum(min_paid)) %>%
  ungroup() %>%
  arrange(date)

# Days below 50k include labor day 2/9/24... what is 27/3/24???
# transactions.agg %>%
#   filter(total_min < 50000)

# Overall time series
ggplot(data = transactions.agg %>% 
         filter(wday(date) != 1 & total_min > 1000) %>%
         filter(date >= dmy("2/1/2024"))) + 
  xlim(dmy("2/1/2024"), dmy("31/12/2024")) + 
  geom_line(aes(x = date, y = total_min))
  

```

```{r compare_max_parking}

excel.estimates <- raw.excel.estimates %>%
  rename(street.ID = "OBJECTID_1",
         estimated.capacity = "est_parking") %>%
  st_drop_geometry()

data.sorted <- data %>%
  arrange(occupancy.buckets) %>%
  st_drop_geometry()

compare_capacity <- data.sorted %>%
  rename(historical_per = "per_100") %>%
  distinct(street.ID, historical_per) %>%
  left_join(excel.estimates) %>%
  mutate(under.utilized = estimated.capacity > historical_per)

ggplot(data = compare_capacity) + 
  geom_point(aes(y = estimated.capacity, x = historical_per, colour = under.utilized)) +
  scale_color_manual(values = c("red", "blue"), guide="none") + 
  geom_abline(aes(intercept=0, slope=1)) + 
  annotate("text", x = 25, y = 30, label = "Underutilized", colour = "blue") + 
  annotate("text", x = 27, y = 22, label = "Over Capacity", colour = "red") + 
  labs(y = "Estimated Parking Capacity", x = "Maximum Occupation")
```


```{r prop-over-target}

streets <- raw.streets %>%
  right_join(compare_capacity) 

ggplot(data = data %>% 
         filter(!is.na(timestamp)) %>%
         filter(wday(timestamp) != 1) %>%
         filter(month(timestamp) == 3 & day(timestamp) == 16) %>%
         filter(street.ID == 12397)) + 
  geom_line(aes(x = timestamp, y = occupied_fraction_99)) +
  geom_abline(aes(intercept=0.8, slope=0), colour = "red") + 
  labs(y = "Occupancy Rate", x = "One day occupancy")

```

```{r compute-toc, fig.height=11, fig.width=11}

data.toc <- data %>%
  mutate(over.capacity = occupied_fraction_99 > 0.8) %>%
  group_by(street.ID, date) %>%
  summarise(toc = sum(over.capacity)) %>%
  arrange(desc(toc))

data.toc %>%
  group_by(street.ID) %>%
  summarise(max_toc = max(toc)) %>%
  arrange(desc(max_toc))
```

```{r toc-plot}


bm <- basemap_ggplot(ext = st_bbox(nov.toc),
                     map_res = 2,
                     map_service = "mapbox", 
                     map_type = "streets", 
                     map_token = mapbox.apikey)

bm +
  xlim(-11856000, -11853000) + 
  ylim(3730500, 3734800) + 
  geom_sf(data = nov.toc %>% st_transform("EPSG:3857"), aes(colour = toc)) + 
  theme_void()

```
